/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.Impl.ImplAlimentoDAO;
import Control.Impl.ImplCardapioDAO;
import Control.Impl.ImplItemCardapioDAO;
import Control.Impl.ImplItemPrescricaoMedica;
import Control.Impl.ImplPrescricaoMedica;
import Model.Alimento;
import Model.Cardapio;
import Model.Idoso;
import Model.ItemCardapio;
import Model.ItemPrescricaoMedica;
import Model.PrescricaoMedica;
import Model.Remedio;
import Util.ComponentValidator;
import Util.DataConverter;
import Util.Mensagens;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author Eduardo
 */
public class FrameCadastroCardapio extends javax.swing.JFrame {

    private List<ItemCardapio> listaItens;
    private List<ItemCardapio> listaItensEdicao;
    private List<ItemCardapio> removidos;
    private List<ItemCardapio> adicionados;
    
    private Cardapio cardapio;
    
    private int cod = 0;
    private int codEdicao = 0;
    
    /**
     * Creates new form CadastroPrescricao
     */
    public FrameCadastroCardapio() {
        initComponents();
        listaItens = new ArrayList<>();
        listaItensEdicao = new ArrayList<>();
        removidos = new ArrayList<>();
        adicionados = new ArrayList<>();
        try {
            List<Alimento> listaR = ImplAlimentoDAO.getInstance().encontrarTodos();
            if(listaR != null) {
                for (Iterator<Alimento> it = listaR.iterator(); it.hasNext();) {
                    Alimento r = it.next();
                    comboBoxAlimento.addItem(r);
                    comboBoxAlimentoEdicao.addItem(r);
                }
            }
        } catch(Exception ex) {
            ex.printStackTrace();
        }
        
    }

    
    private void limparCadastro() {
        campoNome.setText("");
        listaCardapio.removeAll();
        comboBoxAlimento.setSelectedIndex(0);
    }
    
    private void limparEdicao() {
        campoNomeEdicao.setText("");
        listaCardapioEdicao.removeAll();
        comboBoxAlimentoEdicao.setSelectedIndex(0);
        botaoConsultar.setEnabled(false);
        listaItensEdicao.clear();
        adicionados.clear();
        removidos.clear();
        habilitado(false);
    }
    
    private void habilitado(boolean flag) {
        campoNome.setEnabled(flag);
        listaCardapio.setEnabled(flag);
        comboBoxAlimentoEdicao.setEnabled(flag);
        botaoAdicionarEdicao.setEnabled(false);
        botaoRemoverEdicao.setEnabled(false);
    }
    
    private void atualizaCardapio() {
        listaCardapio.setListData(listaItens.toArray());
    }
    
    private void atualizaCardapioEdicao() {
        listaCardapioEdicao.setListData(listaItensEdicao.toArray());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCardapio = new javax.swing.JList();
        botaoAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        comboBoxAlimento = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCardapioEdicao = new javax.swing.JList();
        comboBoxCardapio = new javax.swing.JComboBox();
        botaoAdicionarEdicao = new javax.swing.JButton();
        botaoRemoverEdicao = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoConsultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoNomeEdicao = new javax.swing.JTextField();
        comboBoxAlimentoEdicao = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastra Prescrição Médica");
        setResizable(false);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cardápio"));

        jScrollPane1.setViewportView(listaCardapio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome da refeição: ");

        comboBoxAlimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione alimento" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(comboBoxAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoAdicionar)
                            .addComponent(botaoRemover))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(botaoCadastrar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cardápio"));

        listaCardapioEdicao.setEnabled(false);
        jScrollPane2.setViewportView(listaCardapioEdicao);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        comboBoxCardapio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione cardápio" }));
        comboBoxCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCardapioActionPerformed(evt);
            }
        });

        botaoAdicionarEdicao.setText("Adicionar");
        botaoAdicionarEdicao.setEnabled(false);
        botaoAdicionarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarEdicaoActionPerformed(evt);
            }
        });

        botaoRemoverEdicao.setText("Remover");
        botaoRemoverEdicao.setEnabled(false);
        botaoRemoverEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverEdicaoActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar alterações");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoConsultar.setText("Consultar");
        botaoConsultar.setEnabled(false);
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome da refeição: ");

        campoNomeEdicao.setEnabled(false);

        comboBoxAlimentoEdicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione alimento" }));
        comboBoxAlimentoEdicao.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(comboBoxCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoConsultar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(campoNomeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoSalvar)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoRemoverEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAdicionarEdicao)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxAlimentoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultar))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNomeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoRemoverEdicao)
                            .addComponent(comboBoxAlimentoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoAdicionarEdicao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        Alimento r;
        if(comboBoxAlimento.getSelectedIndex() != 0) {
            r = (Alimento) comboBoxAlimento.getSelectedItem();
        }
        else {
            Mensagens.campoInvalido(this, "Campo Alimento");
            return;
        }
        ItemCardapio ic = new ItemCardapio();
        ic.setNumeroAlimento(r.getCodigo());
        ic.setCod(cod++);
        ic.setAlimento(r);
        listaItens.add(ic);
        atualizaCardapio();
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        Cardapio cardapio = new Cardapio();
        if(!campoNome.getText().equals("")) {
            //cardapio.setNome(campoID.getText());
        }
        else {
            Mensagens.campoInvalido(this, "Campo Nome");
            return;
        }
        if(listaItens.isEmpty()) {
            Mensagens.campoInvalido(this, "Cardapio");
            return;
        }
        try {
            ImplCardapioDAO.getInstance().inserir(cardapio);
            for (Iterator<ItemCardapio> it = listaItens.iterator(); it.hasNext();) {
                ItemCardapio itemCardapio = it.next();
                ImplItemCardapioDAO.getInstance().inserir(itemCardapio);
            }
            limparCadastro();
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        if(!listaCardapio.isSelectionEmpty()) {
            listaItens.remove((ItemCardapio) listaCardapio.getSelectedValue());
            atualizaCardapio();
        }
        else {
            Mensagens.campoInvalido(this, "Alimento Cardapio");
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void botaoAdicionarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarEdicaoActionPerformed
        Alimento r;
        if(comboBoxAlimentoEdicao.getSelectedIndex() != 0) {
            r = (Alimento) comboBoxAlimentoEdicao.getSelectedItem();
        }
        else {
            Mensagens.campoInvalido(this, "Campo Alimento");
            return;
        }
        ItemCardapio iC = new ItemCardapio();
        iC.setNumeroAlimento(r.getCodigo());
        iC.setCod(codEdicao++);
        iC.setAlimento(r);
        listaItensEdicao.add(iC);
        adicionados.add(iC);
        atualizaCardapioEdicao();
    }//GEN-LAST:event_botaoAdicionarEdicaoActionPerformed

    private void botaoRemoverEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverEdicaoActionPerformed
        if(!listaCardapioEdicao.isSelectionEmpty()) {
            listaItensEdicao.remove((ItemCardapio) listaCardapioEdicao.getSelectedValue());
            removidos.add((ItemCardapio) listaCardapioEdicao.getSelectedValue());
            atualizaCardapio();
        }
        else {
            Mensagens.campoInvalido(this, "Alimento cardápio");
        }
    }//GEN-LAST:event_botaoRemoverEdicaoActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        cardapio = (Cardapio) comboBoxCardapio.getSelectedItem();
        if(comboBoxCardapio.getSelectedIndex() != 0) {
            
            listaItensEdicao = new ArrayList<>();
            try {
                listaItensEdicao = ImplItemCardapioDAO.getInstance().encontrarTodos();

                for (Iterator<ItemCardapio> it = listaItensEdicao.iterator(); it.hasNext();) {
                    ItemCardapio itemCardapio = it.next();
                    itemCardapio.setCod(codEdicao++);
                }
            } catch(Exception ex) {
                ex.printStackTrace();
            }
            atualizaCardapioEdicao();
            // campoNomeEdicao.setText(cardapio.getNome());
            comboBoxAlimentoEdicao.setSelectedIndex(0);
            habilitado(true);
        }
        else {
            Mensagens.campoInvalido(this, "Campo Cardápio");
        }
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Cardapio cardapio = new Cardapio();
        if(!campoNomeEdicao.getText().equals("")) {
            //prescricao.setID(campoIDEdicao.getText());
        }
        else {
            Mensagens.campoInvalido(this, "Campo Nome");
            return;
        }
        if(listaItensEdicao.isEmpty()) {
            Mensagens.campoInvalido(this, "Cardápio");
            return;
        }
        try {
            ImplCardapioDAO.getInstance().atualizar(cardapio);
            for (Iterator<ItemCardapio> it = removidos.iterator(); it.hasNext();) {
                ItemCardapio itemCardapio = it.next();
                ImplItemCardapioDAO.getInstance().remover(itemCardapio);
            }
            for (Iterator<ItemCardapio> it = adicionados.iterator(); it.hasNext();) {
                ItemCardapio itemCardapio = it.next();
                ImplItemCardapioDAO.getInstance().inserir(itemCardapio);
            }
            limparEdicao();
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(jTabbedPane1.getSelectedIndex() == 1) {
            try {
                List<Cardapio> lista = ImplCardapioDAO.getInstance().encontrarTodos();
                for (Iterator<Cardapio> it = lista.iterator(); it.hasNext();) {
                    Cardapio cardapio = it.next();
                    comboBoxCardapio.addItem(cardapio);
                }
            } catch(Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void comboBoxCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCardapioActionPerformed
        if(comboBoxCardapio.getSelectedIndex() != 0) {
            botaoConsultar.setEnabled(true);
        }
        else {
            botaoConsultar.setEnabled(false);
        }
    }//GEN-LAST:event_comboBoxCardapioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAdicionarEdicao;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoRemoverEdicao;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeEdicao;
    private javax.swing.JComboBox comboBoxAlimento;
    private javax.swing.JComboBox comboBoxAlimentoEdicao;
    private javax.swing.JComboBox comboBoxCardapio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList listaCardapio;
    private javax.swing.JList listaCardapioEdicao;
    // End of variables declaration//GEN-END:variables
}
