/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.Impl.Exception.DAOException;
import Control.Impl.ImplRemedioDAO;
import Model.Remedio;
import Util.Mensagens;
import View.components_controlers.ComponentControler;
import View.components_controlers.Input;
import View.components_controlers.IntegerFieldContoler;
import View.components_controlers.TextFieldControler;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JComponent;

/**
 *
 * @author Eduardo
 */
public class FrameCadastroRemedio extends javax.swing.JFrame {
    
    // COMPONENTES DA ABA DE CADASTRO
    private static final String KEY_NOME = "nome";
    private static final String KEY_QTD_ESTOQUE = "qtdEstoque";
    private static final String KEY_UNIDADE_MEDIDA = "unidadeMedida";
    private HashMap<String, ComponentControler> componentesCadastro;
    private ArrayList<Input> entradasCadastro;
    
    // COMPONENTES DA ABA DE EDIÇÃO
    private TextFieldControler consulta;
    private HashMap<String, ComponentControler> componentesEdicao;
    private ArrayList<Input> entradasEdicao;
    private Remedio remedio;
    
    /**
     * Creates new form FrameCadastroRemedio
     */
    public FrameCadastroRemedio() {
        initComponents();
        componentesCadastro = new HashMap<>();
        componentesEdicao = new HashMap<>();
        entradasCadastro = new ArrayList<>();
        entradasEdicao = new ArrayList<>();
        TextFieldControler nome = new TextFieldControler(campoNome);
        componentesCadastro.put(KEY_NOME, nome);
        entradasCadastro.add(nome);
        IntegerFieldContoler estoque = new IntegerFieldContoler(campoQntEstoque);
        componentesCadastro.put(KEY_QTD_ESTOQUE, estoque);
        entradasCadastro.add(estoque);
        TextFieldControler unidadeMedida = new TextFieldControler(campoUnidadeMedida);
        componentesCadastro.put(KEY_UNIDADE_MEDIDA, unidadeMedida);
        entradasCadastro.add(unidadeMedida);
        
        consulta = new TextFieldControler(campoConsulta);
        TextFieldControler nomeE = new TextFieldControler(campoNomeEdicao);
        componentesEdicao.put(KEY_NOME, nomeE);
        entradasEdicao.add(nomeE);
        IntegerFieldContoler estoqueE = new IntegerFieldContoler(campoQntEstoqueEdicao);
        componentesEdicao.put(KEY_QTD_ESTOQUE, estoqueE);
        entradasEdicao.add(estoqueE);
        TextFieldControler unidadeMedidaE = new TextFieldControler(campoUnidadeMedidaEdicao);
        componentesEdicao.put(KEY_UNIDADE_MEDIDA, unidadeMedidaE);
        entradasEdicao.add(unidadeMedidaE);
    }
    
    private boolean validaCadastro() {
        for (Iterator<Input> it = entradasCadastro.iterator(); it.hasNext();) {
            Input input = it.next();
            System.out.println("Valido : " + input.isValid());
            if(! input.isValid()) return false;
        }
        return true;
    }
    
    private boolean validaEdicao() {
        for (Iterator<Input> it = entradasEdicao.iterator(); it.hasNext();) {
            Input input = it.next();
            if(! input.isValid()) return false;
        }
        return true;
    }
    
    private void limparCadastro() {
        for (Iterator<ComponentControler> it = componentesCadastro.values().iterator(); it.hasNext();) {
            ComponentControler componentControler = it.next();
            componentControler.limpar();
        }
    }
    
    private void limparEdicao() {
        for (Iterator<ComponentControler> it = componentesEdicao.values().iterator(); it.hasNext();) {
            ComponentControler componentControler = it.next();
            componentControler.limpar();
        }
    }
    
    private void habilitado(boolean flag) {
        for (Iterator<ComponentControler> it = componentesEdicao.values().iterator(); it.hasNext();) {
            ComponentControler componentControler = it.next();
            componentControler.habilitado(flag);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoQntEstoque = new javax.swing.JFormattedTextField();
        botaoCadastrar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        campoUnidadeMedida = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoConsulta = new javax.swing.JTextField();
        botaoConsultar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoUnidadeMedidaEdicao = new javax.swing.JTextField();
        campoQntEstoqueEdicao = new javax.swing.JFormattedTextField();
        campoNomeEdicao = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CadastroRemedio");
        setResizable(false);

        jLabel2.setText("Quantidade em estoque:");

        jLabel1.setText("Nome:");

        jLabel3.setText("Unidade de medida:");

        campoQntEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNome)
                            .addComponent(campoQntEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(campoUnidadeMedida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoQntEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(botaoCadastrar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel4.setText("Nome do remédio:");

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome:");

        jLabel9.setText("Quantidade em estoque:");

        jLabel10.setText("Unidade de medida:");

        campoUnidadeMedidaEdicao.setEnabled(false);

        campoQntEstoqueEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoQntEstoqueEdicao.setEnabled(false);

        campoNomeEdicao.setEnabled(false);

        botaoSalvar.setText("Salvar alterações");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSalvar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNomeEdicao)
                            .addComponent(campoQntEstoqueEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(campoUnidadeMedidaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(campoConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoConsultar)))
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoNomeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoQntEstoqueEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoUnidadeMedidaEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        if(validaCadastro()) {
            Remedio r = new Remedio();
            r.setNomeRemedio((String) componentesCadastro.get(KEY_NOME).getValue());
            r.setQtdEstoque((int) componentesCadastro.get(KEY_QTD_ESTOQUE).getValue());
            r.setUnidadeMedida((String) componentesCadastro.get(KEY_UNIDADE_MEDIDA).getValue());
            try {
                ImplRemedioDAO.getInstance().inserir(r);
                limparCadastro();
                Mensagens.cadastradoComSucesso(this);
            } catch(DAOException ex) {
                ex.printStackTrace();
            }
        }
        else {
            Mensagens.camposInvalidos(this);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        if(consulta.isValid()) {
            try {
                remedio = ImplRemedioDAO.getInstance().encontrarPorNome((String) consulta.getValue());
                if(remedio != null) {
                    habilitado(true);
                    botaoSalvar.setEnabled(true);
                    componentesEdicao.get(KEY_NOME).setValue(remedio.getNomeRemedio());
                    componentesEdicao.get(KEY_QTD_ESTOQUE).setValue(remedio.getQtdEstoque());
                    componentesEdicao.get(KEY_UNIDADE_MEDIDA).setValue(remedio.getUnidadeMedida());
                }
                else {
                    Mensagens.naoEncontradoConsulta(this);
                }
            } catch(Exception ex) {
                ex.printStackTrace();
            }
        }
        else {
            Mensagens.camposInvalidos(this);
        }
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if(validaEdicao()) {
            if(remedio == null) {
                Mensagens.nadaParaAlterar(this);
            }
            else {
                try {
                    Remedio remAtual = new Remedio();
                    remAtual.setCodigo(remedio.getCodigo());
                    remAtual.setNomeRemedio((String) componentesEdicao.get(KEY_NOME).getValue());
                    remAtual.setQtdEstoque((int) componentesEdicao.get(KEY_QTD_ESTOQUE).getValue());
                    remAtual.setUnidadeMedida((String) componentesEdicao.get(KEY_UNIDADE_MEDIDA).getValue());
                    ImplRemedioDAO.getInstance().atualizar(remAtual);
                    Mensagens.alteradoComSucesso(this);
                    consulta.limpar();
                    limparEdicao();
                    remedio = null;
                    habilitado(false);
                    botaoSalvar.setEnabled(false);
                } catch(Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
        else {
            Mensagens.camposInvalidos(this);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoConsulta;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeEdicao;
    private javax.swing.JFormattedTextField campoQntEstoque;
    private javax.swing.JFormattedTextField campoQntEstoqueEdicao;
    private javax.swing.JTextField campoUnidadeMedida;
    private javax.swing.JTextField campoUnidadeMedidaEdicao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
