/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.Impl.Exception.DAOException;
import Control.Impl.ImplQuartoDAO;
import Control.Impl.ImplRemedioDAO;
import Model.Quarto;
import Model.Remedio;
import Util.Mensagens;
import View.components_controlers.ComboBoxControler;
import View.components_controlers.ComponentControler;
import View.components_controlers.Input;
import View.components_controlers.IntegerFieldContoler;
import View.components_controlers.TextFieldControler;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class FrameCadastroQuarto extends javax.swing.JFrame {

    // COMPONENTES DA ABA DE CADASTRO
    private static final String KEY_NUM_QUARTO = "numQuarto";
    private static final String KEY_NUM_ANDAR = "numAndar";
    private static final String KEY_CAPACIDADE = "capacidade";
    private HashMap<String, ComponentControler> componentesCadastro;
    private ArrayList<Input> entradasCadastro;
    
    // COMPONENTES DA ABA DE EDIÇÃO
    private ComboBoxControler consulta;
    private HashMap<String, ComponentControler> componentesEdicao;
    private ArrayList<Input> entradasEdicao;
    private Quarto quarto;
    
    
    /**
     * Creates new form FrameCadastroQuarto
     */
    public FrameCadastroQuarto() {
        initComponents();
        componentesCadastro = new HashMap<>();
        componentesEdicao = new HashMap<>();
        entradasCadastro = new ArrayList<>();
        entradasEdicao = new ArrayList<>();
        IntegerFieldContoler numQuarto = new IntegerFieldContoler(campoNumQuarto);
        componentesCadastro.put(KEY_NUM_QUARTO, numQuarto);
        entradasCadastro.add(numQuarto);
        IntegerFieldContoler numAndar = new IntegerFieldContoler(campoNumAndar);
        componentesCadastro.put(KEY_NUM_ANDAR, numAndar);
        entradasCadastro.add(numAndar);
        IntegerFieldContoler capacidade = new IntegerFieldContoler(campoCapacidade);
        componentesCadastro.put(KEY_CAPACIDADE, capacidade);
        entradasCadastro.add(capacidade);
        
        consulta = new ComboBoxControler(comboBoxConsulta);
        IntegerFieldContoler numQuartoE = new IntegerFieldContoler(campoNumQuartoEdicao);
        componentesEdicao.put(KEY_NUM_QUARTO, numQuartoE);
        entradasEdicao.add(numQuartoE);
        IntegerFieldContoler numAndarE = new IntegerFieldContoler(campoNumAndarEdicao);
        componentesEdicao.put(KEY_NUM_ANDAR, numAndarE);
        entradasEdicao.add(numAndarE);
        IntegerFieldContoler capacidadeE = new IntegerFieldContoler(campoCapacidadeEdicao);
        componentesEdicao.put(KEY_CAPACIDADE, capacidadeE);
        entradasEdicao.add(capacidadeE);
        
    }
    
    private boolean validaCadastro() {
        for (Iterator<Input> it = entradasCadastro.iterator(); it.hasNext();) {
            Input input = it.next();
            System.out.println("Valido : " + input.isValid());
            if(! input.isValid()) return false;
        }
        return true;
    }
    
    private boolean validaEdicao() {
        for (Iterator<Input> it = entradasEdicao.iterator(); it.hasNext();) {
            Input input = it.next();
            if(! input.isValid()) return false;
        }
        return true;
    }
    
    private void limparCadastro() {
        for (Iterator<ComponentControler> it = componentesCadastro.values().iterator(); it.hasNext();) {
            ComponentControler componentControler = it.next();
            componentControler.limpar();
        }
    }
    
    private void limparEdicao() {
        for (Iterator<ComponentControler> it = componentesEdicao.values().iterator(); it.hasNext();) {
            ComponentControler componentControler = it.next();
            componentControler.limpar();
        }
    }
    
    private void habilitado(boolean flag) {
        for (Iterator<ComponentControler> it = componentesEdicao.values().iterator(); it.hasNext();) {
            ComponentControler componentControler = it.next();
            componentControler.habilitado(flag);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        campoNumQuarto = new javax.swing.JFormattedTextField();
        botaoCadastrar = new javax.swing.JButton();
        campoNumAndar = new javax.swing.JFormattedTextField();
        campoCapacidade = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoNumQuartoEdicao = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        campoNumAndarEdicao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        campoCapacidadeEdicao = new javax.swing.JFormattedTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoConsultar = new javax.swing.JButton();
        comboBoxConsulta = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Quarto/Apartamento");
        setResizable(false);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        campoNumQuarto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        campoNumAndar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        campoCapacidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel1.setText("N° do quarto:");

        jLabel2.setText("Capacidade:");

        jLabel3.setText("N° do andar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(botaoCadastrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNumAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrar)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel4.setText("N° do quarto:");

        campoNumQuartoEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoNumQuartoEdicao.setEnabled(false);

        jLabel5.setText("N° do andar:");

        campoNumAndarEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoNumAndarEdicao.setEnabled(false);

        jLabel6.setText("Capacidade:");

        campoCapacidadeEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoCapacidadeEdicao.setEnabled(false);

        botaoSalvar.setText("Salvar alterações");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        comboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione quarto" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCapacidadeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNumAndarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(campoNumQuartoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(133, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoConsultar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(botaoSalvar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConsultar)
                    .addComponent(comboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNumQuartoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNumAndarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoCapacidadeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        if(validaCadastro()) {
            Quarto q = new Quarto();
            q.setNumQuarto((int) componentesCadastro.get(KEY_NUM_ANDAR).getValue());
            q.setNumAndar((int) componentesCadastro.get(KEY_NUM_ANDAR).getValue());
            q.setCapacidade((int) componentesCadastro.get(KEY_CAPACIDADE).getValue());
            q.setEstado(Quarto.ESTADO_DISPONIVEL);
            try {
                ImplQuartoDAO.getInstance().inserir(q);
                limparCadastro();
                Mensagens.cadastradoComSucesso(this);
            } catch(DAOException ex) {
                ex.printStackTrace();
            }
        }
        else {
            Mensagens.camposInvalidos(this);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if(validaEdicao()) {
            if(quarto == null) {
                Mensagens.nadaParaAlterar(this);
            }
            else {
                try {
                    Quarto quaAtual = new Quarto();
                    quaAtual.setNumAndar(quarto.getNumAndar());
                    quaAtual.setNumAndar((int) componentesEdicao.get(KEY_NUM_QUARTO).getValue());
                    quaAtual.setNumAndar((int) componentesEdicao.get(KEY_NUM_ANDAR).getValue());
                    quaAtual.setCapacidade((int) componentesEdicao.get(KEY_CAPACIDADE).getValue());
                    ImplQuartoDAO.getInstance().atualizar(quaAtual);
                    Mensagens.alteradoComSucesso(this);
                    consulta.limpar();
                    limparEdicao();
                    quarto = null;
                    habilitado(false);
                    botaoSalvar.setEnabled(false);
                } catch(Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
        else {
            Mensagens.camposInvalidos(this);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        if(consulta.isValid()) {
            try {
                quarto = ImplQuartoDAO.getInstance().encontrarPorCodigo(((Quarto) consulta.getValue()).getNumQuarto(), ((Quarto) consulta.getValue()).getNumAndar());
                if(quarto != null) {
                    habilitado(true);
                    botaoSalvar.setEnabled(true);
                    componentesEdicao.get(KEY_NUM_QUARTO).setValue(quarto.getNumQuarto());
                    componentesEdicao.get(KEY_NUM_ANDAR).setValue(quarto.getNumAndar());
                    componentesEdicao.get(KEY_CAPACIDADE).setValue(quarto.getCapacidade());
                }
                else {
                    Mensagens.naoEncontradoConsulta(this);
                }
            } catch(Exception ex) {
                ex.printStackTrace();
            }
        }
        else {
            Mensagens.camposInvalidos(this);
        }
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(jTabbedPane1.getSelectedIndex() == 1) {
            try {
                comboBoxConsulta.removeAllItems();
                comboBoxConsulta.addItem("Selecione quarto");
                List<Quarto> lista = ImplQuartoDAO.getInstance().encontrarTodos();
                if(lista != null) {
                    for (Iterator<Quarto> it = lista.iterator(); it.hasNext();) {
                        Quarto q = it.next();
                        consulta.setValue(q);
                    }
                }
            } catch(Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JFormattedTextField campoCapacidade;
    private javax.swing.JFormattedTextField campoCapacidadeEdicao;
    private javax.swing.JFormattedTextField campoNumAndar;
    private javax.swing.JFormattedTextField campoNumAndarEdicao;
    private javax.swing.JFormattedTextField campoNumQuarto;
    private javax.swing.JFormattedTextField campoNumQuartoEdicao;
    private javax.swing.JComboBox comboBoxConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
